### PR TITLE
Dir 5064 - Documentation for Webhook implementation

### PR DESCRIPTION
**Pull request by sathya-direct**
Documentation for Webhook implementation

### CODE REVIEW

**Review by Rgaliant — CHANGES_REQUESTED** [review]
couple requests from me:
is there a way to put all of the webhooks underneath a tab of webhook? similar to how we do with unit and then have all the requests underneath it in the nav, and it can be truncated. Also take away webhook after each one, since it will be redundant once they are all under the webhook menu.
more similar to how guest does it here.
Screen Shot 2022-03-10 at 11 27 44 AM

**Comment by sathya-direct** [comment]
> @Rgaliant Updated documentation to display webhooks in same tab and removed word - 'webhooks'  for all.

**Comment by Rgaliant** [comment]
@sathya-direct hey, we added a couple things. 1 we added the organization id at the top level, we also added unit_id to unit rate and unit availability. Can you add some documentation for that? also can you reach out to bala and ask him to also review this since we have updated some of the implementation?

**Comment by sathya-direct** [comment]
> @sathya-direct hey, we added a couple things. 1 we added the organization id at the top level, we also added unit_id to unit rate and unit availability. Can you add some documentation for that? also can you reach out to bala and ask him to also review this since we have updated some of the implementation? Other than that, it's looking great.

Thanks @Rgaliant . Updated Json's as per the discussion.

**Pull request merged**
